### ISSUE TITLE
Migrate all markdowns to github wiki?

### ISSUE THREAD

**Issue by nbantatua** [proudcloud/awesome#8]
Maybe it would be `awesome` if we move everything into https://github.com/proudcloud/awesome/wiki except the main markdown file, of course.

**Comment by rstacruz** [comment]
it'd give you the exact same functionality wouldnt it? :package:

**Comment by rstacruz** [comment]
...only we'll lose the PR functionality

**Comment by rstacruz** [comment]
hmm, okay... this is a :-1: vote for me:

pros:

- you get a pages list.
- you get a sidebar and footer.

cons:

- github wiki's revision tracking isn't as solid as with full-fledged git repositories.
- images won't be supported. with a git repo, you can place them in images/, but in the wiki you'll probably have to host them in imgur.
- no pull requests.

**Comment by nbantatua** [comment]
Is there no one else?
