### ISSUE TITLE
secrets.yml, application.yml, and everything credentials/keys

### ISSUE THREAD

**Issue by nbantatua** [proudcloud/awesome#9]
From where we left off at [4d5b36b], can we settle for best practice approach for handling credentials/keys?

again, my pitch would be:
- Take every kind of credentials/keys as *sensitive*, hence, avoid hardcoding any, especially in environment config files & initializers
- Check in `secrets.yml` as part of the repo.
- Use `application.yml` as well, but do not include in repo
- All sensitive credentials set from `application.yml` are to be set from `secrets.yml`
- Use `Rails.application.secrets` in calling these credentials
- Refrain from using `ENV`
- Check-in `secrets.yml.sample` and `application.yml.sample` in repo to provide other devs the necessary key names for credentials(and/or even provide actual dev environment credentials/keys)

[4d5b36b]:https://github.com/proudcloud/awesome/pull/6#discussion_r30666329

**Comment by rstacruz** [comment]
application.yml shouldn't exist unless you're using figaro, afaik.

checking in secrets.yml.example is redundant if you're checking in secrets.yml already.

also, all proudcloud projects i stumbled onto have .yml files checked in

**Comment by rstacruz** [comment]
also it was probably @victorsolis or @jasontorres who started the "check in secrets.yml" trend so i'll leave that to them haha.

**Comment by nbantatua** [comment]
I agree.

**Comment by victorsolis** [comment]
Wasn't me lol. But that should only be done for private repos.

**Comment by rstacruz** [comment]
commiting secrets.yml is okay for me.

it does seem fundamentally wrong. for private repositories, though, you might as well consider the *entire* code repository as a company secret, anyway. moving those secret credentials (api tokens) away into somewhere else (possibly less secure like evernote) can be simply thought of as an exercise in security through obscurity.

also it's very convenient not needing to update secrets.yml whenever it needs to change.

**Comment by nbantatua** [comment]
if that's the agreed case, we're good.
